remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
description: "Data analytics portfolio by Swati Mirashi, showcasing projects, dashboards, and insights that blend technical skills, problem-solving, and statistical analysis to drive data-informed business decisions."
